{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Histogram quantile",
   "type": "graph",
   "description": "Histogram quantile rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "ui HTTP error",
   "type": "graph",
   "description": "Add HTTP requests with error status",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "UI HTTP Request",
   "type": "graph",
   "description": "All HTTP Request that UI interface receive",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[23].*\"}[1m])"
    }
   ]
  }
 ]
}